[package]
name = "lstatus"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[dependencies]
i3ipc = "^0.9.0"
serde = "^1.0.80"
serde_derive = "^1.0.80"
serde_json = "^1.0.33"

[[bin]]
name = "lstatus"
path = "src/bin.rs"
